name: absenteeism_v2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  card_swiper : ^2.0.1
  intro_slider: ^3.0.0
  get: ^4.1.4
  table_calendar: ^3.0.1
  flutter_spinkit: ^5.2.0
  retrofit: '>=4.0.0 <5.0.0'
  flutter_native_splash: ^1.2.1
  dio: ^5.2.1
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
